### ISSUE TITLE
xml output error xml.etree.ElementTree.ParseError: syntax error: line 1, column 0

### ISSUE THREAD

**Issue by ySlag** [nmmapper/python3-nmap#38]
Hi, 
I have installed python3-nmap today and when I am running the  scan_command with param -oX (or -oA) it does create the xml and insert the result correctly but it also returns the below error: 

```Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/nmap3/nmap3.py", line 261, in get_xml_et
    return ET.fromstring(command_output)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1320, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nmapscript.py", line 25, in <module>
    res = nmap.scan_command(target, '-p 22','-oA scan')
  File "/usr/local/lib/python3.8/dist-packages/nmap3/nmap3.py", line 102, in scan_command
    xml_root = self.get_xml_et(output)
  File "/usr/local/lib/python3.8/dist-packages/nmap3/nmap3.py", line 262, in get_xml_et
    except xml.etree.ElementTree.ParseError:
NameError: name 'xml' is not defined
```

I am calling the param as follow: 

```
import nmap3

nmap = nmap3.Nmap()
target = "192.168.226.130"
res = nmap.scan_command(target, '-p 22','-oA scan')

```
As looking at the output of one of the scan the command executed is 
```
# Nmap 7.91 scan initiated Mon Nov 30 22:16:36 2020 as: /usr/bin/nmap -oX - -p 22 -oA scan 192.168.226.130
```

Not sure if the repetition of the -o might be causing the problem, though running it manually doesn't return any error.
Am I doing something not supported/correct? 

Thanks

**Comment by f-froehlich** [comment]
Hi,
First of all the second exception is solved in the current master branch. The main exception caused because there is an error during parsing the output of nmap. If you set `-oA scan` there is no xml returned from the nmap command to the cli:
```
/usr/bin/nmap -oX - -p 22 -oA scan 192.168.0.11
Starting Nmap 7.80 ( https://nmap.org ) at 2020-12-06 15:23 CET
Nmap scan report for 192.168.0.11
Host is up (0.00026s latency).

PORT   STATE SERVICE
22/tcp open  ssh

Nmap done: 1 IP address (1 host up) scanned in 0.05 seconds

```

Remove the param `-oA scan` to get the scan output as xml to the CLI or add `-oX -` after `-oA scan`. Please also be sure that nmap is installed and you can execute nmap as your running user. You might need sudo for it (add it in /etc/sudoers and don't execut the python script as root)
Also You shouldn't use the `Nmap` class. Use `NmapScanTechniques` instead because it is a bit easier to use. Also you should check out https://github.com/nmmapper/python3-nmap/pull/35 

Best whishes
